### ISSUE TITLE
Can't add ideas

### ISSUE THREAD

**Issue by hello-kathi** [liqd/zt-app#246] opened 2022-01-28 07:53 UTC
**URL:** 
**user:** participant
**expected behaviour:** I am going to a project with a running phase and can add an idea 
**behaviour:** There nothing (no button, typo etc) where I can hit and add an idea
**important screensize:**
**device & browser:** iPhone xr ios 15.1
**Comment/Question:** Screenshots show the whole page 

Screenshot?
![photo_2022-01-28_08-51-37](https://user-images.githubusercontent.com/52459078/151508135-48d8adff-065d-41bc-9c30-119066f471c6.jpg)

![photo_2022-01-28_08-51-32](https://user-images.githubusercontent.com/52459078/151508181-0878082e-d549-4c48-8214-2302dd742d97.jpg)

![photo_2022-01-28_08-51-28](https://user-images.githubusercontent.com/52459078/151508232-2f9bada6-f64d-46aa-8b70-2f3748149330.jpg)

**Comment by Rineee** [comment] 2022-01-31 09:43
@hello-kathi yes, thats annoying, we are already on.. thats a duplicate of #206, so will close!

**Closed by Rineee** 2022-01-31 09:43 UTC
