### ISSUE TITLE
IdeaProject image styling broken / wrong size

### ISSUE THREAD

**Issue by goapunk** [liqd/zt-app#258] opened 2022-02-08 09:27 UTC
**URL:** 
**user:** 
**expected behaviour:** Image is shown correctly
**behaviour:** Image is resized based on the size of the whole container, thus only showing a fraction of it if there's a lot of comments*
**important screensize:**
**device & browser:** any 
**Comment/Question:** 

Screenshot?

**Comment by fuzzylogic2000** [comment] 2022-07-18 13:45
Is this still there after @phillimorland s redo?

**Comment by fuzzylogic2000** [comment] 2022-07-18 14:09
will close this as the duplicate of #328 as @phillimorland s PR will fix that issue

**Closed by fuzzylogic2000** 2022-07-18 14:09 UTC
Labels: Dev: Styling, Type: Bug

**Comment by phillimorland** [comment] 2022-07-19 07:49
i'll take a look, I think I only did the form image styling
