### ISSUE TITLE
header image issue

### ISSUE THREAD

**Issue by lthueer** [liqd/zt-app#328] opened 2022-07-12 12:54 UTC
**URL:** https://aplus-dev.liqd.net/teststadt-luca/projects/app-testing/
**user:** all
**expected behaviour:** header image stays the same when changing tabs (info, participation, result)
**behaviour:** project header image changes format and get blurred when tab participation is selected
**important screensize:**
**device & browser:** Google Pixel 4a (Android 12)
**Commen
![Screenshot_20220712-145129](https://user-images.githubusercontent.com/36957474/178494737-3a39e7da-ce96-40f0-8447-32e2c53a827d.png)
![Screenshot_20220712-145132](https://user-images.githubusercontent.com/36957474/178494745-8a3d5903-3ca2-4e1a-8718-398c59713d71.png)
t/Question:**

**Comment by lthueer** [comment] 2022-07-18 09:32
note: also when information and result tab is switched the image size changes depending on how much text etc. is there in each tab

**Comment by fuzzylogic2000** [comment] 2022-07-18 13:48
isn't this a duplicate of #258 ?

**Closed** 2022-07-19 09:31 UTC
